{
  "openapi": "3.0.0",
  "info": {
    "title": "FGAtlas-API-Docs",
    "description": "API com objetivo de abastecer a aplicação FGAtlas",
    "contacts": "kauaponte@hotmail.com",
    "version": "1.0.0"
  },
  "paths": {
    "/subject": {
      "get": {
        "summary": "Pegar todas as matérias",
        "description": "Rota responsável por pegar todas as matérias do banco de dados",
        "tags": [
          "Subject"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Subject"
              },
              "examples": {
                "subject": {
                  "value": {
                    "codeId": "FGA0003",
                    "name": "Compiladores",
                    "class": 1
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a subject"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/subject/{codeId}": {
      "get": {
        "summary": "Pegar uma matéria em específico",
        "description": "Rota responsável por pegar uma matéria do banco de dados",
        "tags": [
          "Subject"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Subject"
              },
              "examples": {
                "Subject": {
                  "value": {
                    "codeId": "FGA0003",
                    "name": "Compiladores",
                    "class": 1
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a subject"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/class": {
      "get": {
        "summary": "Pegar todas as turmas",
        "description": "Rota responsável por pegar todas as turmas do banco de dados",
        "tags": [
          "Class"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Class"
              },
              "examples": {
                "Class": {
                  "value": {
                    "id": 1,
                    "idClass": 1,
                    "subjectCodeId": "FGA0003",
                    "teacher": "EDSON ALVES DA COSTA JUNIOR",
                    "room": 2,
                    "timeAndDay": "46T23"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a turma"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/class/{idClass}": {
      "get": {
        "summary": "Pegar uma turma em específico",
        "description": "Rota responsável por pegar uma turma em específico do banco de dados",
        "tags": [
          "Class"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Class"
              },
              "examples": {
                "Class": {
                  "value": {
                    "id": 1,
                    "idClass": 1,
                    "subjectCodeId": "FGA0003",
                    "teacher": "EDSON ALVES DA COSTA JUNIOR",
                    "room": 2,
                    "timeAndDay": "46T23"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a turma"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/class/subject/{subjectCodeId}": {
      "get": {
        "summary": "Pegar todas as turmas de uma matéria específica",
        "description": "Rota responsável por pegar uma turma de uma matéria específica do banco de dados",
        "tags": [
          "Class"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Class"
              },
              "examples": {
                "Class": {
                  "value": {
                    "id": 1,
                    "idClass": 1,
                    "subjectCodeId": "FGA0003",
                    "teacher": "EDSON ALVES DA COSTA JUNIOR",
                    "room": 2,
                    "timeAndDay": "46T23"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a turma"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/building": {
      "get": {
        "summary": "Pegar todos os prédios",
        "description": "Rota responsável por pegar todos os prédios do banco de dados",
        "tags": [
          "Building"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Building"
              },
              "examples": {
                "Building": {
                  "value": {
                    "name": "RU",
                    "latitude": "-15.98956996870734",
                    "longitude": "-48.0442005874793",
                    "rooms": "0"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar o prédio"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/building/{name}": {
      "get": {
        "summary": "Pegar um prédio em específico",
        "description": "Rota responsável por pegar um prédio em específico",
        "tags": [
          "Building"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Building"
              },
              "examples": {
                "Building": {
                  "value": {
                    "name": "RU",
                    "latitude": "-15.98956996870734",
                    "longitude": "-48.0442005874793",
                    "rooms": 0
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar o prédio"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/rooms": {
      "get": {
        "summary": "Pegar todas as salas",
        "description": "Rota responsável por pegar todas as salas do banco de dados",
        "tags": [
          "Room"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Room"
              },
              "examples": {
                "Room": {
                  "value": {
                    "buildingName": "UAC",
                    "latitude": "-15.989186",
                    "longitude": "-48.044865",
                    "class": 13,
                    "level": 1,
                    "identification": "ANFITEATRO"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a sala"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    },
    "/room/{identification}": {
      "get": {
        "summary": "Pegar uma sala em específico",
        "description": "Rota responsável por pegar uma sala do banco de dados",
        "tags": [
          "Room"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Room"
              },
              "examples": {
                "Room": {
                  "value": {
                    "buildingName": "UAC",
                    "latitude": "-15.989186",
                    "longitude": "-48.044865",
                    "class": 13,
                    "level": 1,
                    "identification": "ANFITEATRO"
                  }
                }
              },
              "responses": {
                "200": {
                  "description": "Extraido com sucesso, pode retornar um array vazio caso não encontrar a sala"
                },
                "404": {
                  "description": "Array vazio ou não encontrado"
                },
                "400": {
                  "description": "Bad request"
                }
              }
            }
          }
        }
      }
    }
    
  },
  "components": {
    "schemas": {
      "Subject": {
        "type": "object",
        "properties": {
          "codeId": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "Class": {
            "type": "Class"
          }
        }
      },
      "Building": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "latitude": {
            "type": "number"
          },
          "longitude": {
            "type": "number"
          },
          "rooms": {
            "type": "Room"
          }
        }
      },
      "Room": {
        "type": "object",
        "properties": {
          "identification": {
            "type": "string"
          },
          "level": {
            "type": "number"
          },
          "latitude": {
            "type": "number"
          },
          "longitude": {
            "type": "number"
          },
          "building": {
            "type": "Building"
          },
          "buildingName": {
            "type": "string"
          },
          "class": {
            "type": "Class"
          }
        }
      },
      "Class": {
        "type": "object",
        "properties": {
          "id": {
            "type": "number"
          },
          "idClass": {
            "type": "number"
          },
          "timeAndDay": {
            "type": "string"
          },
          "teacher": {
            "type": "string"
          },
          "subject": {
            "type": "Subject"
          },
          "subjectCodeId": {
            "type": "string"
          },
          "room": {
            "type": "Room"
          }
        }
      }
    }
  }
}